import type { OpeningState } from '@/lib/mahjong/opening';
import { FLOWER_NAMES } from '@/lib/mahjong/opening';
import { MahjongFace } from './mahjong-face';
const dots:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
export function OpeningSequence({opening,names,onRoll,onSkip}:{opening:OpeningState;names:string[];onRoll:()=>void;onSkip:()=>void}){
 const current=opening.events[opening.index],sum=opening.dice.reduce((a,b)=>a+b,0),rolled=opening.index>=3;
 const dealt=current.counts.reduce((a,b)=>a+b,0),replacements=opening.events.slice(0,opening.index+1).filter(e=>e.kind==='flowers').reduce((n,e)=>n+(e.flowers?.length??0),0),cut=(opening.breakSide*36+sum*2)%144;
 const taken=(side:number,stack:number,layer:number)=>{if(!rolled)return false;const position=(side*36+stack*2+layer-cut+144)%144;return position<dealt||position>=144-replacements;};
 const title={shuffle:'洗牌',stack:'疊牌', 'dice-wait':'擲骰開門',dice:'擲骰',break:'開門拎牌',deal:'輪流拎牌',flowers:'攤花・補花',ready:'執好牌，準備出牌'}[current.kind];
 const detail=current.kind==='deal'?`${names[current.player!]} 拎${current.count===4?'兩棟（四張）':current.count===2?'莊家跳牌（兩張）':'一張'}`:current.kind==='flowers'?`${names[current.player!]} 摸到 ${current.flowers!.map(i=>FLOWER_NAMES[i]).join('、')}，從牌尾補牌`:rolled?`${sum} 點 · ${names[opening.breakSide]} 面前牌牆，第 ${opening.breakStack} 棟後開門`:'每邊十八棟，一棟兩張';
 return <section className={`opening-sequence stage-${current.kind}`} aria-label="開局儀式"><div className="opening-heading" role="status"><h2>{title}</h2><p>{detail}</p></div><div className="opening-board">
 {current.kind==='shuffle'?<div className="shuffle-tiles">{Array.from({length:36},(_,i)=><i key={i} style={{left:`${12+(i*23)%72}%`,top:`${10+(i*37)%75}%`,animationDelay:`${-i*.09}s`}}/>)}</div>:<>{[0,1,2,3].map(side=><div key={side} className={`opening-wall side-${side}`}>{Array.from({length:18},(_,i)=><i key={i} className={rolled&&side===opening.breakSide&&i===opening.breakStack-1?'wall-break':''}><b className={taken(side,i,1)?'taken-tile':''}/><b className={taken(side,i,0)?'taken-tile':''}/></i>)}</div>)}<div className={`dice-tray ${current.kind==='dice'?'rolling':''}`}>{opening.dice.map((value,i)=><div key={i} className={`die ${value===1||value===4?'red-die':''}`} aria-label={rolled?`${value} 點`:'未擲骰'}>{Array.from({length:9},(_,n)=><i key={n} className={rolled&&dots[value].includes(n)?'pip':''}/>)}</div>)}</div>{current.kind==='deal'&&<div key={opening.index} className={`taking-stack to-player-${current.player}`}><i/><i/><span>{names[current.player!]} +{current.count}</span></div>}{current.kind==='flowers'&&<div className="opening-flowers">{current.flowers!.map(f=><div className="tile" key={f}><MahjongFace tile={{flower:f}}/></div>)}</div>}</>}
 </div><div className="dealt-counts">{names.map((name,i)=><span key={i} className={current.player===i?'dealing':''}>{name}<b>{current.counts[i]} 張</b></span>)}</div><div className="opening-actions">{current.kind==='dice-wait'&&<button className="roll-dice" onClick={onRoll}>擲骰</button>}<button onClick={onSkip}>跳過動畫</button></div></section>;
}
