/* data.js — catalog, categories, UI strings.
 * 16 products per category map 1:1 to a 4x4 sprite sheet (cell 0..15).
 * Sheet id is decoupled from category so we can extend later (electronics-2.png).
 * Compact tuple format expands into window.PRODUCTS below.
 *   tuple = [en, zh, price, listPrice, rating, ratingCount, sellerEn, sellerZh, [tags]]
 */
(function () {
  const CAT_META = {
    electronics: { en: 'Electronics',      zh: '電子產品', icon: '📱', color: '#e6f0ff' },
    fashion:     { en: 'Fashion',          zh: '時裝',     icon: '👗', color: '#ffe9f0' },
    home:        { en: 'Home & Kitchen',   zh: '家居廚具', icon: '🏠', color: '#e8f8ef' },
    beauty:      { en: 'Beauty',           zh: '美妝個護', icon: '💄', color: '#fdeaf5' },
    grocery:     { en: 'Grocery',          zh: '超市百貨', icon: '🛒', color: '#fff3e0' },
    toys:        { en: 'Toys & Games',     zh: '玩具遊戲', icon: '🧸', color: '#eef0ff' },
    sports:      { en: 'Sports & Outdoors',zh: '運動戶外', icon: '⚽', color: '#e8f5ff' },
    books:       { en: 'Books & Stationery',zh: '圖書文具',icon: '📚', color: '#f3eaff' },
  };

  const RAW = {
    electronics: [
      ['Wireless Noise-Cancelling Headphones', '無線降噪耳機', 599, 999, 4.6, 2381, 'AudioMax', 'AudioMax 官方旗艦店', ['headphones', '耳機', 'bluetooth', '降噪']],
      ['True Wireless Earbuds', '真無線藍牙耳機', 399, 599, 4.4, 5120, 'SoundPods', 'SoundPods 旗艦店', ['earbuds', '耳機', '藍牙']],
      ['Smartphone 128GB', '智能手機 128GB', 2999, 3599, 4.7, 8932, 'TechNova', 'TechNova 官方店', ['phone', '手機', 'smartphone']],
      ['Fitness Smartwatch', '智能運動手錶', 699, 1099, 4.3, 3045, 'PulseFit', 'PulseFit 旗艦店', ['watch', '手錶', 'fitness']],
      ['Slim 14" Laptop', '超薄 14 吋手提電腦', 5499, 6999, 4.6, 1290, 'TechNova', 'TechNova 官方店', ['laptop', '電腦', 'notebook']],
      ['Portable Bluetooth Speaker', '便攜藍牙喇叭', 299, 499, 4.5, 4210, 'SoundPods', 'SoundPods 旗艦店', ['speaker', '喇叭', 'bluetooth']],
      ['Mechanical Keyboard', '機械鍵盤', 459, 599, 4.7, 2670, 'KeyCraft', 'KeyCraft 鍵盤專門店', ['keyboard', '鍵盤', 'mechanical']],
      ['Wireless Gaming Mouse', '無線電競滑鼠', 249, 349, 4.4, 3380, 'KeyCraft', 'KeyCraft 鍵盤專門店', ['mouse', '滑鼠', 'gaming']],
      ['10" Tablet with Stylus', '10 吋平板連手寫筆', 1899, 2299, 4.5, 1560, 'TechNova', 'TechNova 官方店', ['tablet', '平板', 'stylus']],
      ['20000mAh Power Bank', '20000mAh 流動充電器', 179, 259, 4.6, 7820, 'VoltGo', 'VoltGo 充電專家', ['powerbank', '尿袋', '充電']],
      ['USB-C Fast Charging Cable', 'USB-C 快充線', 59, 99, 4.3, 9100, 'VoltGo', 'VoltGo 充電專家', ['cable', '充電線', 'usb-c']],
      ['1080p Clip-on Webcam', '1080p 夾式網絡攝影機', 229, 329, 4.2, 1040, 'ClearView', 'ClearView 影像', ['webcam', '攝影機', '視像']],
      ['Foldable Mini Drone', '摺疊迷你航拍機', 1299, 1799, 4.4, 860, 'SkyShot', 'SkyShot 航拍', ['drone', '航拍', '無人機']],
      ['4K Action Camera', '4K 運動攝錄機', 999, 1399, 4.5, 1720, 'ClearView', 'ClearView 影像', ['camera', '運動相機', '4k']],
      ['27" Thin-Bezel Monitor', '27 吋窄邊框顯示器', 1199, 1599, 4.6, 2050, 'ClearView', 'ClearView 影像', ['monitor', '顯示器', '螢幕']],
      ['VR Headset', 'VR 虛擬實境眼鏡', 1999, 2499, 4.3, 640, 'TechNova', 'TechNova 官方店', ['vr', '虛擬實境', '遊戲']],
    ],
    fashion: [
      ['Cotton Crew-Neck T-Shirt', '純棉圓領T恤', 89, 129, 4.5, 6300, 'UrbanThread', '城線時裝', ['tshirt', 't恤', 'cotton']],
      ['Slim-Fit Denim Jeans', '修身牛仔褲', 299, 459, 4.4, 4120, 'UrbanThread', '城線時裝', ['jeans', '牛仔褲', 'denim']],
      ['White Leather Sneakers', '白色皮革運動鞋', 499, 799, 4.6, 5210, 'StepUp', 'StepUp 鞋履', ['sneakers', '波鞋', 'shoes']],
      ['Leather Crossbody Bag', '真皮斜揹袋', 399, 699, 4.5, 2380, 'LuxeCarry', 'LuxeCarry 皮具', ['bag', '袋', 'leather']],
      ['Hooded Sweatshirt', '連帽衛衣', 239, 359, 4.5, 3900, 'UrbanThread', '城線時裝', ['hoodie', '衛衣', '帽T']],
      ['Wool Overcoat', '羊毛大褸', 899, 1499, 4.4, 1180, 'UrbanThread', '城線時裝', ['coat', '大褸', 'wool']],
      ['Floral Summer Dress', '碎花連身裙', 359, 559, 4.6, 2740, 'BloomWear', '綻放女裝', ['dress', '連身裙', 'floral']],
      ['Leather Strap Watch', '皮帶手錶', 459, 799, 4.3, 1560, 'Tempo', 'Tempo 鐘錶', ['watch', '手錶', 'leather']],
      ['Aviator Sunglasses', '飛行員太陽眼鏡', 199, 329, 4.4, 3010, 'SunVeil', 'SunVeil 眼鏡', ['sunglasses', '太陽眼鏡', 'eyewear']],
      ['Knit Beanie', '針織冷帽', 79, 119, 4.5, 2200, 'UrbanThread', '城線時裝', ['beanie', '冷帽', 'knit']],
      ['Leather Belt', '真皮皮帶', 149, 249, 4.4, 1890, 'LuxeCarry', 'LuxeCarry 皮具', ['belt', '皮帶', 'leather']],
      ['Running Shoes', '跑步鞋', 549, 799, 4.6, 4600, 'StepUp', 'StepUp 鞋履', ['running', '跑鞋', 'shoes']],
      ['Patterned Silk Scarf', '印花絲巾', 129, 199, 4.3, 980, 'BloomWear', '綻放女裝', ['scarf', '絲巾', 'silk']],
      ['Baseball Cap', '棒球帽', 99, 149, 4.5, 3300, 'UrbanThread', '城線時裝', ['cap', '帽', 'baseball']],
      ['Ankle Boots', '短靴', 699, 999, 4.4, 1420, 'StepUp', 'StepUp 鞋履', ['boots', '短靴', 'shoes']],
      ['Canvas Backpack', '帆布背囊', 329, 499, 4.6, 3870, 'LuxeCarry', 'LuxeCarry 皮具', ['backpack', '背囊', 'bag']],
    ],
    home: [
      ['Electric Kettle', '電熱水壺', 199, 299, 4.6, 5200, 'HomeNest', '家窩家品', ['kettle', '水壺', 'kitchen']],
      ['Ceramic Coffee Mug', '陶瓷咖啡杯', 59, 89, 4.5, 7300, 'HomeNest', '家窩家品', ['mug', '杯', 'ceramic']],
      ['Nonstick Frying Pan', '不黏煎鍋', 159, 259, 4.4, 3100, 'ChefLine', '廚匠', ['pan', '煎鍋', 'kitchen']],
      ['Stand Mixer', '座枱式攪拌機', 1299, 1799, 4.7, 940, 'ChefLine', '廚匠', ['mixer', '攪拌機', 'baking']],
      ['Drinking Glasses (Set of 6)', '玻璃水杯(6隻裝)', 129, 199, 4.5, 2600, 'HomeNest', '家窩家品', ['glass', '水杯', 'set']],
      ['Scented Candle', '香薰蠟燭', 89, 139, 4.6, 4100, 'AuraHome', '氛圍家居', ['candle', '蠟燭', 'scented']],
      ['Knit Throw Pillow', '針織抱枕', 119, 179, 4.4, 1800, 'AuraHome', '氛圍家居', ['pillow', '抱枕', 'cushion']],
      ['Modern Table Lamp', '現代座枱燈', 249, 399, 4.5, 1500, 'AuraHome', '氛圍家居', ['lamp', '枱燈', 'light']],
      ['Wood Cutting Board', '木砧板', 99, 159, 4.6, 2900, 'ChefLine', '廚匠', ['board', '砧板', 'wood']],
      ["Chef's Knife", '廚師刀', 179, 289, 4.7, 2100, 'ChefLine', '廚匠', ['knife', '刀', 'kitchen']],
      ['French Press', '法式壓濾壺', 139, 219, 4.4, 1600, 'BrewCraft', '沖泡工房', ['coffee', '咖啡壺', 'press']],
      ['Dinner Plate Set', '餐碟套裝', 199, 299, 4.5, 2400, 'HomeNest', '家窩家品', ['plate', '餐碟', 'set']],
      ['Bath Towel', '浴巾', 69, 109, 4.5, 5600, 'CottonCloud', '棉雲', ['towel', '浴巾', 'bath']],
      ['Monstera in Pot', '龜背竹盆栽', 159, 239, 4.6, 1300, 'GreenLeaf', '綠葉植栽', ['plant', '盆栽', 'green']],
      ['Minimalist Wall Clock', '簡約掛鐘', 99, 159, 4.4, 2000, 'AuraHome', '氛圍家居', ['clock', '掛鐘', 'wall']],
      ['Air Purifier', '空氣清新機', 899, 1299, 4.5, 1700, 'PureAir', '淨氣', ['purifier', '空氣清新機', 'air']],
    ],
    beauty: [
      ['Vitamin C Serum', '維他命C精華', 189, 289, 4.6, 6200, 'GlowLab', '光研', ['serum', '精華', 'skincare']],
      ['Hydrating Face Cream', '保濕面霜', 159, 239, 4.5, 5400, 'GlowLab', '光研', ['cream', '面霜', 'skincare']],
      ['Matte Lipstick', '啞光唇膏', 119, 179, 4.4, 8300, 'Rouge', '胭脂彩妝', ['lipstick', '唇膏', 'makeup']],
      ['Eau de Parfum', '女士香水', 399, 599, 4.6, 2100, 'Essence', '馥香', ['perfume', '香水', 'fragrance']],
      ['Makeup Brush Set', '化妝掃套裝', 149, 249, 4.5, 3200, 'Rouge', '胭脂彩妝', ['brush', '化妝掃', 'makeup']],
      ['Ionic Hair Dryer', '負離子風筒', 459, 699, 4.5, 2700, 'SleekHair', '順髮', ['dryer', '風筒', 'hair']],
      ['Eyeshadow Palette', '眼影盤', 169, 259, 4.4, 3600, 'Rouge', '胭脂彩妝', ['eyeshadow', '眼影', 'makeup']],
      ['Electric Toothbrush', '電動牙刷', 299, 459, 4.6, 4100, 'FreshDent', '潔齒', ['toothbrush', '牙刷', 'dental']],
      ['Sheet Mask (10pcs)', '面膜(10片)', 99, 159, 4.5, 9200, 'GlowLab', '光研', ['mask', '面膜', 'skincare']],
      ['Sunscreen SPF50', '防曬乳 SPF50', 129, 189, 4.6, 5100, 'GlowLab', '光研', ['sunscreen', '防曬', 'skincare']],
      ['Nail Polish', '指甲油', 49, 79, 4.3, 2400, 'Rouge', '胭脂彩妝', ['nail', '指甲油', 'makeup']],
      ['Liquid Foundation', '液體粉底', 179, 269, 4.4, 3800, 'Rouge', '胭脂彩妝', ['foundation', '粉底', 'makeup']],
      ['Hair Straightener', '直髮夾', 329, 499, 4.5, 2300, 'SleekHair', '順髮', ['straightener', '直髮夾', 'hair']],
      ['Cleansing Facial Brush', '潔面儀', 249, 399, 4.4, 1500, 'GlowLab', '光研', ['cleansing', '潔面儀', 'skincare']],
      ["Men's Cologne", '男士古龍水', 359, 539, 4.5, 1800, 'Essence', '馥香', ['cologne', '古龍水', 'fragrance']],
      ['Cotton Pads (200pcs)', '化妝棉(200片)', 39, 59, 4.6, 7600, 'GlowLab', '光研', ['cotton', '化妝棉', 'beauty']],
    ],
    grocery: [
      ['Fresh Bananas (1kg)', '新鮮香蕉(1公斤)', 15, 22, 4.4, 3200, 'FreshMart', '鮮市', ['banana', '香蕉', 'fruit']],
      ['Red Apples (6pcs)', '紅蘋果(6個)', 29, 39, 4.5, 2800, 'FreshMart', '鮮市', ['apple', '蘋果', 'fruit']],
      ['Fresh Milk 1L', '鮮牛奶 1公升', 19, 25, 4.6, 5400, 'DairyBest', '醇牛奶', ['milk', '牛奶', 'dairy']],
      ['Sliced Bread', '切片麵包', 16, 22, 4.3, 4100, 'BakeHouse', '烘焙坊', ['bread', '麵包', 'bakery']],
      ['Eggs (12pcs)', '雞蛋(12隻)', 28, 36, 4.5, 6200, 'FarmFresh', '農鮮', ['egg', '雞蛋', 'dairy']],
      ['Coffee Beans 500g', '咖啡豆 500克', 89, 129, 4.6, 1900, 'BrewCraft', '沖泡工房', ['coffee', '咖啡豆', 'drink']],
      ['Dark Chocolate Bar', '黑朱古力', 25, 35, 4.5, 3300, 'CocoaJoy', '可可樂', ['chocolate', '朱古力', 'snack']],
      ['Olive Oil 1L', '橄欖油 1公升', 69, 99, 4.6, 2100, 'PureKitchen', '純廚', ['oil', '橄欖油', 'cooking']],
      ['Breakfast Cereal', '早餐穀物', 45, 65, 4.3, 2700, 'MorningCrunch', '晨脆', ['cereal', '穀物', 'breakfast']],
      ['Fresh Broccoli', '西蘭花', 12, 18, 4.4, 1800, 'FreshMart', '鮮市', ['broccoli', '西蘭花', 'vegetable']],
      ['Pasta 500g', '意大利麵 500克', 18, 26, 4.5, 2400, 'PureKitchen', '純廚', ['pasta', '意粉', 'food']],
      ['Pure Honey', '純正蜜糖', 79, 119, 4.6, 1500, 'BeeNature', '蜂然', ['honey', '蜜糖', 'natural']],
      ['Orange Juice 1L', '橙汁 1公升', 22, 32, 4.4, 3600, 'FreshMart', '鮮市', ['juice', '橙汁', 'drink']],
      ['Cheddar Cheese Block', '車打芝士', 55, 79, 4.5, 1700, 'DairyBest', '醇牛奶', ['cheese', '芝士', 'dairy']],
      ['Jasmine Rice 5kg', '香米 5公斤', 89, 119, 4.7, 4900, 'GoldenGrain', '金穀', ['rice', '米', 'staple']],
      ['Avocados (2pcs)', '牛油果(2個)', 26, 38, 4.3, 2200, 'FreshMart', '鮮市', ['avocado', '牛油果', 'fruit']],
    ],
    toys: [
      ['Plush Teddy Bear', '毛公仔泰迪熊', 149, 229, 4.7, 3400, 'CuddleToys', '抱抱玩具', ['teddy', '毛公仔', 'plush']],
      ['Building Blocks (200pcs)', '積木(200塊)', 199, 299, 4.6, 5100, 'BrickWorld', '積木世界', ['blocks', '積木', 'building']],
      ['Toy Sports Car', '玩具跑車', 79, 119, 4.4, 2600, 'SpeedyToys', '風馳玩具', ['car', '玩具車', 'toy']],
      ['Wooden Train Set', '木製火車組', 259, 399, 4.6, 1700, 'WoodPlay', '木趣', ['train', '火車', 'wooden']],
      ['Jigsaw Puzzle 1000pcs', '拼圖 1000塊', 99, 149, 4.5, 2200, 'MindGames', '腦力遊戲', ['puzzle', '拼圖', 'jigsaw']],
      ['Family Board Game', '家庭桌上遊戲', 229, 329, 4.6, 1900, 'MindGames', '腦力遊戲', ['boardgame', '桌遊', 'game']],
      ['Speed Cube', '扭計骰', 49, 79, 4.5, 4300, 'MindGames', '腦力遊戲', ['cube', '扭計骰', 'puzzle']],
      ['Remote Control Car', '遙控車', 299, 459, 4.4, 2100, 'SpeedyToys', '風馳玩具', ['rc', '遙控車', 'toy']],
      ['Stacking Rings Toy', '疊疊圈嬰兒玩具', 79, 119, 4.6, 1500, 'CuddleToys', '抱抱玩具', ['baby', '嬰兒玩具', 'stacking']],
      ['Superhero Action Figure', '超級英雄模型', 129, 199, 4.5, 2800, 'HeroLine', '英雄系列', ['figure', '模型', 'action']],
      ['Fashion Doll', '時裝娃娃', 99, 159, 4.4, 2400, 'CuddleToys', '抱抱玩具', ['doll', '娃娃', 'toy']],
      ['Toy Dinosaur', '玩具恐龍', 69, 109, 4.5, 2000, 'SpeedyToys', '風馳玩具', ['dinosaur', '恐龍', 'toy']],
      ['Pro Yo-Yo', '專業搖搖', 39, 59, 4.3, 1600, 'SpeedyToys', '風馳玩具', ['yoyo', '搖搖', 'toy']],
      ['Diamond Kite', '菱形風箏', 59, 89, 4.4, 1100, 'SkyPlay', '天際玩樂', ['kite', '風箏', 'outdoor']],
      ['Toy Kitchen Stove', '玩具廚房爐', 199, 299, 4.5, 1300, 'WoodPlay', '木趣', ['kitchen', '玩具廚房', 'pretend']],
      ['Marble Run Set', '彈珠軌道組', 169, 259, 4.6, 1700, 'BrickWorld', '積木世界', ['marble', '彈珠', 'building']],
    ],
    sports: [
      ['Yoga Mat', '瑜伽墊', 129, 199, 4.6, 4200, 'FlexFit', '柔伸', ['yoga', '瑜伽墊', 'fitness']],
      ['Dumbbell Pair', '啞鈴一對', 199, 299, 4.5, 3100, 'IronCore', '鐵芯', ['dumbbell', '啞鈴', 'fitness']],
      ['Basketball', '籃球', 119, 179, 4.5, 2700, 'ProBall', '球品', ['basketball', '籃球', 'sport']],
      ['Soccer Ball', '足球', 99, 149, 4.4, 2400, 'ProBall', '球品', ['soccer', '足球', 'sport']],
      ['Tennis Racket', '網球拍', 299, 459, 4.5, 1500, 'ProBall', '球品', ['tennis', '網球拍', 'sport']],
      ['Athletic Running Shoes', '運動跑鞋', 499, 749, 4.6, 3800, 'StepUp', 'StepUp 鞋履', ['running', '跑鞋', 'shoes']],
      ['Insulated Water Bottle', '保溫水樽', 89, 139, 4.6, 5300, 'HydroGo', '水動', ['bottle', '水樽', 'hydration']],
      ['Resistance Bands Set', '阻力帶套裝', 79, 119, 4.5, 3600, 'FlexFit', '柔伸', ['bands', '阻力帶', 'fitness']],
      ['Bicycle Helmet', '單車頭盔', 199, 299, 4.4, 1700, 'RideSafe', '安騎', ['helmet', '頭盔', 'cycling']],
      ['2-Person Camping Tent', '雙人露營帳篷', 599, 899, 4.5, 1200, 'WildCamp', '野營', ['tent', '帳篷', 'camping']],
      ['Hiking Backpack 40L', '行山背囊 40L', 459, 699, 4.6, 1400, 'WildCamp', '野營', ['backpack', '背囊', 'hiking']],
      ['Speed Jump Rope', '競速跳繩', 49, 79, 4.4, 2900, 'FlexFit', '柔伸', ['rope', '跳繩', 'fitness']],
      ['Skateboard', '滑板', 299, 459, 4.5, 1800, 'BoardLab', '板研', ['skateboard', '滑板', 'sport']],
      ['Foam Roller', '泡沫滾筒', 99, 149, 4.5, 2100, 'FlexFit', '柔伸', ['roller', '滾筒', 'recovery']],
      ['Kettlebell 8kg', '壺鈴 8公斤', 179, 259, 4.6, 1600, 'IronCore', '鐵芯', ['kettlebell', '壺鈴', 'fitness']],
      ['Insulated Cooler Box', '保溫冰桶', 329, 499, 4.4, 1100, 'WildCamp', '野營', ['cooler', '冰桶', 'outdoor']],
    ],
    books: [
      ['Hardcover Novel', '精裝小說', 129, 179, 4.6, 3200, 'PagePress', '書頁', ['book', '小說', 'novel']],
      ['Paperback Book Set', '平裝書套裝', 199, 299, 4.5, 1800, 'PagePress', '書頁', ['book', '叢書', 'set']],
      ['Spiral Notebook', '螺旋筆記本', 29, 45, 4.5, 5600, 'InkWell', '墨井', ['notebook', '筆記本', 'stationery']],
      ['Colored Pencils (48)', '顏色鉛筆(48色)', 79, 119, 4.6, 3400, 'ColorCraft', '彩繪', ['pencils', '顏色筆', 'art']],
      ['Fountain Pen', '鋼筆', 159, 249, 4.5, 2100, 'InkWell', '墨井', ['pen', '鋼筆', 'writing']],
      ['Leather Journal', '皮革筆記簿', 119, 189, 4.6, 2700, 'InkWell', '墨井', ['journal', '筆記簿', 'leather']],
      ['Desk Organizer', '桌面收納座', 99, 149, 4.4, 1900, 'DeskMate', '桌伴', ['organizer', '收納', 'desk']],
      ['Sticky Notes Pad', '便利貼', 19, 29, 4.5, 7200, 'InkWell', '墨井', ['sticky', '便利貼', 'stationery']],
      ['Highlighter Set', '螢光筆套裝', 39, 59, 4.4, 3300, 'ColorCraft', '彩繪', ['highlighter', '螢光筆', 'stationery']],
      ['Ballpoint Pens (10)', '原子筆(10支)', 25, 39, 4.5, 6100, 'InkWell', '墨井', ['pen', '原子筆', 'stationery']],
      ['Sketchbook', '素描簿', 59, 89, 4.6, 2400, 'ColorCraft', '彩繪', ['sketchbook', '素描簿', 'art']],
      ['Bookends (Pair)', '書立(一對)', 89, 139, 4.4, 1300, 'DeskMate', '桌伴', ['bookends', '書立', 'desk']],
      ['Desk Calculator', '桌面計算機', 69, 99, 4.5, 2800, 'DeskMate', '桌伴', ['calculator', '計算機', 'office']],
      ['Stapler', '釘書機', 39, 59, 4.4, 3100, 'DeskMate', '桌伴', ['stapler', '釘書機', 'office']],
      ['Daily Planner', '日程計劃本', 79, 119, 4.6, 2200, 'InkWell', '墨井', ['planner', '計劃本', 'stationery']],
      ['Watercolor Paint Set', '水彩顏料套裝', 129, 199, 4.5, 1700, 'ColorCraft', '彩繪', ['watercolor', '水彩', 'art']],
    ],
  };

  // ---- expand tuples into product objects ----
  const PRODUCTS = [];
  const BY_ID = {};
  let n = 0;
  Object.keys(RAW).forEach((cat) => {
    RAW[cat].forEach((row, i) => {
      n += 1;
      const id = 'p' + String(n).padStart(3, '0');
      const p = {
        id,
        title: { en: row[0], zh: row[1] },
        price: row[2],
        listPrice: row[3],
        rating: row[4],
        ratingCount: row[5],
        seller: { en: row[6], zh: row[7] },
        tags: row[8],
        category: cat,
        sheet: cat,   // first sheet per category; extend with `${cat}-2`, etc.
        cell: i,      // 0..15 within the 4x4 sheet
      };
      PRODUCTS.push(p);
      BY_ID[id] = p;
    });
  });

  const CATEGORIES = Object.keys(CAT_META).map((id) => ({
    id,
    name: { en: CAT_META[id].en, zh: CAT_META[id].zh },
    icon: CAT_META[id].icon,
    color: CAT_META[id].color,
  }));
  const CAT_BY_ID = {};
  CATEGORIES.forEach((c) => { CAT_BY_ID[c.id] = c; });

  window.PRODUCTS = PRODUCTS;
  window.CATEGORIES = CATEGORIES;
  window.CAT_BY_ID = CAT_BY_ID;
  window.getProduct = (id) => BY_ID[id];

  // ---- UI strings (bilingual) ----
  window.UI = {
    brand:        { en: 'CoolShop', zh: '爽購' },
    tagline:      { en: 'Shop all you want — checkout is always free', zh: '盡情購物，結帳永遠免費' },
    searchPlaceholder: { en: 'Search products', zh: '搜尋商品' },
    navHome:      { en: 'Home', zh: '首頁' },
    navCats:      { en: 'Categories', zh: '分類' },
    navCart:      { en: 'Cart', zh: '購物車' },
    navOrders:    { en: 'Orders', zh: '訂單' },
    navMe:        { en: 'Me', zh: '我的' },
    addToCart:    { en: 'Add to Cart', zh: '加入購物車' },
    buyNow:       { en: 'Buy Now', zh: '立即購買' },
    added:        { en: 'Added to cart', zh: '已加入購物車' },
    subtotal:     { en: 'Subtotal', zh: '小計' },
    total:        { en: 'Total', zh: '合計' },
    checkout:     { en: 'Checkout', zh: '去結帳' },
    placeOrder:   { en: 'Place Order — Free', zh: '免費下單' },
    emptyCart:    { en: 'Your cart is empty', zh: '購物車是空的' },
    emptyCartHint:{ en: 'Browse products and add your favourites', zh: '去逛逛，加入心水商品吧' },
    goShopping:   { en: 'Go Shopping', zh: '去購物' },
    orderPlaced:  { en: 'Order Placed!', zh: '下單成功！' },
    youSaved:     { en: 'You saved', zh: '你慳返' },
    savedTotal:   { en: 'Total money saved', zh: '累積慳返' },
    freeCheckoutNote: { en: 'No payment needed — enjoy the thrill, keep your money.', zh: '無需付款 — 盡享購物快感，慳低荷包。' },
    orderId:      { en: 'Order', zh: '訂單編號' },
    reviewsTitle: { en: 'Customer Reviews', zh: '顧客評價' },
    verified:     { en: 'Verified Purchase', zh: '已驗證購買' },
    seller:       { en: 'Sold by', zh: '賣家' },
    description:  { en: 'Description', zh: '商品描述' },
    qty:          { en: 'Qty', zh: '數量' },
    remove:       { en: 'Remove', zh: '移除' },
    sortBy:       { en: 'Sort', zh: '排序' },
    sortPop:      { en: 'Popularity', zh: '人氣' },
    sortPriceAsc: { en: 'Price: Low to High', zh: '價格：低至高' },
    sortPriceDesc:{ en: 'Price: High to Low', zh: '價格：高至低' },
    sortRating:   { en: 'Rating', zh: '評分' },
    sortDiscount: { en: 'Biggest Discount', zh: '最大折扣' },
    noResults:    { en: 'No products found', zh: '找不到商品' },
    resultsFor:   { en: 'Results for', zh: '搜尋結果' },
    flashDeals:   { en: 'Flash Deals', zh: '限時優惠' },
    recommended:  { en: 'Recommended for You', zh: '為你推薦' },
    allCategories:{ en: 'All Categories', zh: '所有分類' },
    login:        { en: 'Log In', zh: '登入' },
    loginName:    { en: 'Enter a username', zh: '輸入用戶名' },
    logout:       { en: 'Log Out', zh: '登出' },
    guest:        { en: 'Guest', zh: '訪客' },
    hello:        { en: 'Hi', zh: '你好' },
    myOrders:     { en: 'My Orders', zh: '我的訂單' },
    noOrders:     { en: 'No orders yet', zh: '未有訂單' },
    noOrdersHint: { en: 'Your placed orders will appear here', zh: '你下單後會在此顯示' },
    items:        { en: 'items', zh: '件' },
    continueShopping: { en: 'Continue Shopping', zh: '繼續購物' },
    viewOrders:   { en: 'View Orders', zh: '查看訂單' },
    backToShop:   { en: 'Back to shopping', zh: '返回購物' },
    ratingsCount: { en: 'ratings', zh: '個評分' },
    settings:     { en: 'Settings', zh: '設定' },
    storeTheme:   { en: 'Store Theme', zh: '商店主題' },
    themeDesc:    { en: 'Pick the look of your store', zh: '選擇商店的外觀風格' },
    language:     { en: 'Language', zh: '語言' },
    themeTaobao:  { en: 'Taobao', zh: '淘寶風' },
    themeAmazon:  { en: 'Amazon', zh: 'Amazon 風' },
    themeHktv:    { en: 'HKTVmall', zh: 'HKTVmall 風' },
    merchOfficial:{ en: 'Official Store', zh: '自營旗艦' },
    merchFreeShip:{ en: 'Free Shipping', zh: '免運費' },
    merchReturn:  { en: '7-Day Returns', zh: '7天退換' },
    merchFast:    { en: '1–4 Day Delivery', zh: '1-4日送達' },
    save:         { en: 'Save', zh: '儲存' },
    savedMsg:     { en: 'Settings saved', zh: '設定已儲存' },
    saveHint:     { en: 'Changes apply after you save', zh: '儲存後才會套用' },
  };
})();
