/* Instant-Dict EC4900H — embedded English↔Chinese wordlist.
 * Each entry: { en, pos, zh, py?, example?, syn?, ant?, deriv? } */
window.DICT = [
  { en: "apple",     pos: "n.",   zh: "蘋果",       py: "píng guǒ",
    example: { en: "An apple a day keeps the doctor away.", zh: "一日一蘋果，醫生遠離我。" },
    syn: ["fruit"], deriv: ["applet"] },
  { en: "apricot",   pos: "n.",   zh: "杏",         py: "xìng" },
  { en: "banana",    pos: "n.",   zh: "香蕉",       py: "xiāng jiāo",
    example: { en: "Monkeys love bananas.", zh: "猴子喜歡香蕉。" } },
  { en: "orange",    pos: "n.",   zh: "橙;橘子",    py: "chéng",
    example: { en: "Orange juice is rich in vitamin C.", zh: "橙汁富含維他命C。" } },
  { en: "grape",     pos: "n.",   zh: "葡萄",       py: "pú táo" },
  { en: "watermelon",pos: "n.",   zh: "西瓜",       py: "xī guā" },
  { en: "pear",      pos: "n.",   zh: "梨",         py: "lí" },
  { en: "peach",     pos: "n.",   zh: "桃",         py: "táo" },
  { en: "lemon",     pos: "n.",   zh: "檸檬",       py: "níng méng" },
  { en: "mango",     pos: "n.",   zh: "芒果",       py: "máng guǒ" },
  { en: "strawberry",pos: "n.",   zh: "草莓",       py: "cǎo méi" },
  { en: "cherry",    pos: "n.",   zh: "櫻桃",       py: "yīng táo" },
  { en: "pineapple", pos: "n.",   zh: "菠蘿;鳳梨",  py: "bō luó" },

  { en: "rice",      pos: "n.",   zh: "米;飯",      py: "mǐ" },
  { en: "noodle",    pos: "n.",   zh: "麵條",       py: "miàn tiáo" },
  { en: "bread",     pos: "n.",   zh: "麵包",       py: "miàn bāo" },
  { en: "egg",       pos: "n.",   zh: "蛋;雞蛋",    py: "dàn" },
  { en: "milk",      pos: "n.",   zh: "牛奶",       py: "niú nǎi" },
  { en: "water",     pos: "n.",   zh: "水",         py: "shuǐ",
    example: { en: "Drink eight glasses of water a day.", zh: "每天喝八杯水。" } },
  { en: "tea",       pos: "n.",   zh: "茶",         py: "chá" },
  { en: "coffee",    pos: "n.",   zh: "咖啡",       py: "kā fēi" },
  { en: "sugar",     pos: "n.",   zh: "糖",         py: "táng" },
  { en: "salt",      pos: "n.",   zh: "鹽",         py: "yán" },
  { en: "soup",      pos: "n.",   zh: "湯",         py: "tāng" },
  { en: "fish",      pos: "n.",   zh: "魚",         py: "yú" },
  { en: "meat",      pos: "n.",   zh: "肉",         py: "ròu" },
  { en: "chicken",   pos: "n.",   zh: "雞",         py: "jī" },
  { en: "pork",      pos: "n.",   zh: "豬肉",       py: "zhū ròu" },
  { en: "beef",      pos: "n.",   zh: "牛肉",       py: "niú ròu" },
  { en: "vegetable", pos: "n.",   zh: "蔬菜",       py: "shū cài" },
  { en: "fruit",     pos: "n.",   zh: "水果",       py: "shuǐ guǒ", syn: ["produce"] },

  { en: "cat",       pos: "n.",   zh: "貓",         py: "māo",
    example: { en: "The cat is sleeping on the sofa.", zh: "貓在沙發上睡覺。" } },
  { en: "dog",       pos: "n.",   zh: "狗",         py: "gǒu" },
  { en: "bird",      pos: "n.",   zh: "鳥",         py: "niǎo" },
  { en: "horse",     pos: "n.",   zh: "馬",         py: "mǎ" },
  { en: "cow",       pos: "n.",   zh: "牛",         py: "niú" },
  { en: "pig",       pos: "n.",   zh: "豬",         py: "zhū" },
  { en: "sheep",     pos: "n.",   zh: "羊",         py: "yáng" },
  { en: "rabbit",    pos: "n.",   zh: "兔子",       py: "tù zi" },
  { en: "tiger",     pos: "n.",   zh: "老虎",       py: "lǎo hǔ" },
  { en: "lion",      pos: "n.",   zh: "獅子",       py: "shī zi" },
  { en: "elephant",  pos: "n.",   zh: "大象",       py: "dà xiàng" },
  { en: "monkey",    pos: "n.",   zh: "猴子",       py: "hóu zi" },
  { en: "panda",     pos: "n.",   zh: "熊貓",       py: "xióng māo" },
  { en: "dragon",    pos: "n.",   zh: "龍",         py: "lóng" },
  { en: "snake",     pos: "n.",   zh: "蛇",         py: "shé" },
  { en: "mouse",     pos: "n.",   zh: "老鼠;滑鼠",  py: "lǎo shǔ" },

  { en: "head",      pos: "n.",   zh: "頭",         py: "tóu" },
  { en: "hand",      pos: "n.",   zh: "手",         py: "shǒu" },
  { en: "foot",      pos: "n.",   zh: "腳",         py: "jiǎo" },
  { en: "eye",       pos: "n.",   zh: "眼睛",       py: "yǎn jīng" },
  { en: "ear",       pos: "n.",   zh: "耳朵",       py: "ěr duo" },
  { en: "nose",      pos: "n.",   zh: "鼻子",       py: "bí zi" },
  { en: "mouth",     pos: "n.",   zh: "嘴",         py: "zuǐ" },
  { en: "tooth",     pos: "n.",   zh: "牙齒",       py: "yá chǐ" },
  { en: "heart",     pos: "n.",   zh: "心;心臟",    py: "xīn" },
  { en: "hair",      pos: "n.",   zh: "頭髮",       py: "tóu fa" },
  { en: "face",      pos: "n.",   zh: "臉",         py: "liǎn" },
  { en: "arm",       pos: "n.",   zh: "手臂",       py: "shǒu bì" },
  { en: "leg",       pos: "n.",   zh: "腿",         py: "tuǐ" },

  { en: "sun",       pos: "n.",   zh: "太陽",       py: "tài yáng" },
  { en: "moon",      pos: "n.",   zh: "月亮",       py: "yuè liang" },
  { en: "star",      pos: "n.",   zh: "星星",       py: "xīng xing" },
  { en: "sky",       pos: "n.",   zh: "天空",       py: "tiān kōng" },
  { en: "cloud",     pos: "n.",   zh: "雲",         py: "yún" },
  { en: "rain",      pos: "n./v.",zh: "雨;下雨",    py: "yǔ" },
  { en: "snow",      pos: "n./v.",zh: "雪;下雪",    py: "xuě" },
  { en: "wind",      pos: "n.",   zh: "風",         py: "fēng" },
  { en: "storm",     pos: "n.",   zh: "暴風雨",     py: "bào fēng yǔ" },
  { en: "thunder",   pos: "n.",   zh: "雷;打雷",    py: "léi" },
  { en: "rainbow",   pos: "n.",   zh: "彩虹",       py: "cǎi hóng" },

  { en: "fire",      pos: "n.",   zh: "火",         py: "huǒ" },
  { en: "earth",     pos: "n.",   zh: "地球;泥土",  py: "dì qiú" },
  { en: "mountain",  pos: "n.",   zh: "山",         py: "shān" },
  { en: "river",     pos: "n.",   zh: "河",         py: "hé" },
  { en: "sea",       pos: "n.",   zh: "海",         py: "hǎi" },
  { en: "ocean",     pos: "n.",   zh: "海洋",       py: "hǎi yáng" },
  { en: "lake",      pos: "n.",   zh: "湖",         py: "hú" },
  { en: "tree",      pos: "n.",   zh: "樹",         py: "shù" },
  { en: "flower",    pos: "n.",   zh: "花",         py: "huā" },
  { en: "grass",     pos: "n.",   zh: "草",         py: "cǎo" },
  { en: "leaf",      pos: "n.",   zh: "葉子",       py: "yè zi" },

  { en: "house",     pos: "n.",   zh: "房子",       py: "fáng zi" },
  { en: "home",      pos: "n.",   zh: "家",         py: "jiā" },
  { en: "school",    pos: "n.",   zh: "學校",       py: "xué xiào" },
  { en: "office",    pos: "n.",   zh: "辦公室",     py: "bàn gōng shì" },
  { en: "shop",      pos: "n.",   zh: "商店",       py: "shāng diàn" },
  { en: "store",     pos: "n.",   zh: "商店",       py: "shāng diàn", syn: ["shop"] },
  { en: "hospital",  pos: "n.",   zh: "醫院",       py: "yī yuàn" },
  { en: "library",   pos: "n.",   zh: "圖書館",     py: "tú shū guǎn" },
  { en: "bank",      pos: "n.",   zh: "銀行",       py: "yín háng" },
  { en: "park",      pos: "n.",   zh: "公園",       py: "gōng yuán" },
  { en: "city",      pos: "n.",   zh: "城市",       py: "chéng shì" },
  { en: "country",   pos: "n.",   zh: "國家;鄉村",  py: "guó jiā" },
  { en: "street",    pos: "n.",   zh: "街道",       py: "jiē dào" },
  { en: "road",      pos: "n.",   zh: "路;道路",    py: "lù" },
  { en: "bridge",    pos: "n.",   zh: "橋",         py: "qiáo" },
  { en: "airport",   pos: "n.",   zh: "機場",       py: "jī chǎng" },
  { en: "station",   pos: "n.",   zh: "車站",       py: "chē zhàn" },

  { en: "car",       pos: "n.",   zh: "汽車",       py: "qì chē" },
  { en: "bus",       pos: "n.",   zh: "巴士;公車",  py: "bā shì" },
  { en: "train",     pos: "n.",   zh: "火車",       py: "huǒ chē" },
  { en: "plane",     pos: "n.",   zh: "飛機",       py: "fēi jī", syn: ["airplane","aircraft"] },
  { en: "ship",      pos: "n.",   zh: "船",         py: "chuán" },
  { en: "boat",      pos: "n.",   zh: "小船",       py: "xiǎo chuán" },
  { en: "bicycle",   pos: "n.",   zh: "自行車",     py: "zì xíng chē", syn: ["bike"] },
  { en: "taxi",      pos: "n.",   zh: "計程車;的士",py: "jì chéng chē" },

  { en: "computer",  pos: "n.",   zh: "電腦;計算機",py: "diàn nǎo" },
  { en: "phone",     pos: "n.",   zh: "電話",       py: "diàn huà" },
  { en: "internet",  pos: "n.",   zh: "互聯網",     py: "hù lián wǎng" },
  { en: "email",     pos: "n.",   zh: "電子郵件",   py: "diàn zǐ yóu jiàn" },
  { en: "screen",    pos: "n.",   zh: "螢幕;屏幕",  py: "yíng mù" },
  { en: "keyboard",  pos: "n.",   zh: "鍵盤",       py: "jiàn pán" },
  { en: "battery",   pos: "n.",   zh: "電池",       py: "diàn chí" },
  { en: "camera",    pos: "n.",   zh: "相機",       py: "xiàng jī" },
  { en: "robot",     pos: "n.",   zh: "機械人",     py: "jī xiè rén" },

  { en: "book",      pos: "n.",   zh: "書",         py: "shū" },
  { en: "pen",       pos: "n.",   zh: "筆",         py: "bǐ" },
  { en: "paper",     pos: "n.",   zh: "紙",         py: "zhǐ" },
  { en: "letter",    pos: "n.",   zh: "信;字母",    py: "xìn" },
  { en: "word",      pos: "n.",   zh: "詞;單字",    py: "cí" },
  { en: "language",  pos: "n.",   zh: "語言",       py: "yǔ yán" },
  { en: "dictionary",pos: "n.",   zh: "字典;辭典",  py: "zì diǎn",
    example: { en: "Look it up in the dictionary.", zh: "查一下字典。" } },
  { en: "news",      pos: "n.",   zh: "新聞;消息",  py: "xīn wén" },

  { en: "father",    pos: "n.",   zh: "父親;爸爸",  py: "fù qīn", syn: ["dad"] },
  { en: "mother",    pos: "n.",   zh: "母親;媽媽",  py: "mǔ qīn", syn: ["mom","mum"] },
  { en: "brother",   pos: "n.",   zh: "兄弟",       py: "xiōng dì" },
  { en: "sister",    pos: "n.",   zh: "姐妹",       py: "jiě mèi" },
  { en: "son",       pos: "n.",   zh: "兒子",       py: "ér zi" },
  { en: "daughter",  pos: "n.",   zh: "女兒",       py: "nǚ ér" },
  { en: "child",     pos: "n.",   zh: "孩子",       py: "hái zi", deriv: ["children","childhood"] },
  { en: "boy",       pos: "n.",   zh: "男孩",       py: "nán hái" },
  { en: "girl",      pos: "n.",   zh: "女孩",       py: "nǚ hái" },
  { en: "man",       pos: "n.",   zh: "男人",       py: "nán rén" },
  { en: "woman",     pos: "n.",   zh: "女人",       py: "nǚ rén" },
  { en: "kid",       pos: "n.",   zh: "小孩",       py: "xiǎo hái" },
  { en: "baby",      pos: "n.",   zh: "嬰兒;寶寶",  py: "yīng ér" },
  { en: "husband",   pos: "n.",   zh: "丈夫",       py: "zhàng fū" },
  { en: "wife",      pos: "n.",   zh: "妻子",       py: "qī zi" },
  { en: "lover",     pos: "n.",   zh: "情人",       py: "qíng rén" },
  { en: "family",    pos: "n.",   zh: "家庭",       py: "jiā tíng" },
  { en: "friend",    pos: "n.",   zh: "朋友",       py: "péng yǒu" },
  { en: "teacher",   pos: "n.",   zh: "老師",       py: "lǎo shī" },
  { en: "student",   pos: "n.",   zh: "學生",       py: "xué sheng" },
  { en: "doctor",    pos: "n.",   zh: "醫生",       py: "yī shēng" },
  { en: "nurse",     pos: "n.",   zh: "護士",       py: "hù shì" },

  { en: "good",      pos: "adj.", zh: "好",         py: "hǎo", ant: ["bad"] },
  { en: "bad",       pos: "adj.", zh: "壞;不好",    py: "huài", ant: ["good"] },
  { en: "big",       pos: "adj.", zh: "大",         py: "dà", ant: ["small"] },
  { en: "small",     pos: "adj.", zh: "小",         py: "xiǎo", ant: ["big"], syn: ["little"] },
  { en: "tall",      pos: "adj.", zh: "高",         py: "gāo", ant: ["short"] },
  { en: "short",     pos: "adj.", zh: "短;矮",      py: "duǎn", ant: ["tall","long"] },
  { en: "long",      pos: "adj.", zh: "長",         py: "cháng", ant: ["short"] },
  { en: "high",      pos: "adj.", zh: "高",         py: "gāo", ant: ["low"] },
  { en: "low",       pos: "adj.", zh: "低",         py: "dī", ant: ["high"] },
  { en: "fast",      pos: "adj.", zh: "快",         py: "kuài", ant: ["slow"], syn: ["quick","rapid"] },
  { en: "slow",      pos: "adj.", zh: "慢",         py: "màn", ant: ["fast"] },
  { en: "hot",       pos: "adj.", zh: "熱;辣",      py: "rè", ant: ["cold"] },
  { en: "cold",      pos: "adj.", zh: "冷",         py: "lěng", ant: ["hot"] },
  { en: "warm",      pos: "adj.", zh: "暖",         py: "nuǎn", ant: ["cool"] },
  { en: "cool",      pos: "adj.", zh: "涼;酷",      py: "liáng", ant: ["warm"] },
  { en: "old",       pos: "adj.", zh: "舊;老",      py: "jiù", ant: ["new","young"] },
  { en: "new",       pos: "adj.", zh: "新",         py: "xīn", ant: ["old"] },
  { en: "young",     pos: "adj.", zh: "年輕",       py: "nián qīng", ant: ["old"] },
  { en: "happy",     pos: "adj.", zh: "快樂;開心",  py: "kuài lè", ant: ["sad"], syn: ["glad","joyful"] },
  { en: "sad",       pos: "adj.", zh: "傷心;難過",  py: "shāng xīn", ant: ["happy"] },
  { en: "angry",     pos: "adj.", zh: "生氣",       py: "shēng qì" },
  { en: "tired",     pos: "adj.", zh: "累;疲倦",    py: "lèi" },
  { en: "busy",      pos: "adj.", zh: "忙",         py: "máng", ant: ["free"] },
  { en: "easy",      pos: "adj.", zh: "容易;簡單",  py: "róng yì", ant: ["hard","difficult"] },
  { en: "hard",      pos: "adj.", zh: "硬;困難",    py: "yìng", ant: ["soft","easy"] },
  { en: "difficult", pos: "adj.", zh: "困難",       py: "kùn nán", ant: ["easy"] },
  { en: "beautiful", pos: "adj.", zh: "美麗;漂亮",  py: "měi lì", syn: ["pretty","lovely"], ant: ["ugly"] },
  { en: "ugly",      pos: "adj.", zh: "醜",         py: "chǒu", ant: ["beautiful"] },
  { en: "rich",      pos: "adj.", zh: "富有",       py: "fù yǒu", ant: ["poor"] },
  { en: "poor",      pos: "adj.", zh: "窮;可憐",    py: "qióng", ant: ["rich"] },
  { en: "clean",     pos: "adj.", zh: "乾淨",       py: "gān jìng", ant: ["dirty"] },
  { en: "dirty",     pos: "adj.", zh: "骯髒",       py: "āng zāng", ant: ["clean"] },
  { en: "right",     pos: "adj.", zh: "對;右",      py: "duì", ant: ["wrong","left"] },
  { en: "wrong",     pos: "adj.", zh: "錯",         py: "cuò", ant: ["right"] },
  { en: "true",      pos: "adj.", zh: "真;真實",    py: "zhēn", ant: ["false"] },
  { en: "false",     pos: "adj.", zh: "假;錯誤",    py: "jiǎ", ant: ["true"] },

  { en: "go",        pos: "v.",   zh: "去",         py: "qù", ant: ["come"], deriv: ["going","gone","went"] },
  { en: "come",      pos: "v.",   zh: "來",         py: "lái", ant: ["go"] },
  { en: "eat",       pos: "v.",   zh: "吃",         py: "chī" },
  { en: "drink",     pos: "v./n.",zh: "喝;飲料",    py: "hē" },
  { en: "sleep",     pos: "v./n.",zh: "睡覺",       py: "shuì jiào" },
  { en: "wake",      pos: "v.",   zh: "醒;喚醒",    py: "xǐng" },
  { en: "run",       pos: "v.",   zh: "跑;經營",    py: "pǎo" },
  { en: "walk",      pos: "v.",   zh: "走;步行",    py: "zǒu" },
  { en: "jump",      pos: "v.",   zh: "跳",         py: "tiào" },
  { en: "sit",       pos: "v.",   zh: "坐",         py: "zuò" },
  { en: "stand",     pos: "v.",   zh: "站",         py: "zhàn" },
  { en: "speak",     pos: "v.",   zh: "說;講",      py: "shuō", syn: ["talk","say"] },
  { en: "talk",      pos: "v./n.",zh: "說話;交談",  py: "tán", syn: ["speak"] },
  { en: "listen",    pos: "v.",   zh: "聽",         py: "tīng", syn: ["hear"] },
  { en: "hear",      pos: "v.",   zh: "聽見",       py: "tīng jiàn" },
  { en: "see",       pos: "v.",   zh: "看見",       py: "kàn", syn: ["look","watch"] },
  { en: "look",      pos: "v.",   zh: "看",         py: "kàn" },
  { en: "watch",     pos: "v./n.",zh: "觀看;手錶",  py: "kàn" },
  { en: "read",      pos: "v.",   zh: "讀;閱讀",    py: "dú" },
  { en: "write",     pos: "v.",   zh: "寫",         py: "xiě", deriv: ["writer","writing","wrote"] },
  { en: "draw",      pos: "v.",   zh: "畫;拉",      py: "huà" },
  { en: "play",      pos: "v.",   zh: "玩;演奏",    py: "wán" },
  { en: "sing",      pos: "v.",   zh: "唱歌",       py: "chàng" },
  { en: "dance",     pos: "v./n.",zh: "跳舞",       py: "tiào wǔ" },
  { en: "buy",       pos: "v.",   zh: "買",         py: "mǎi", ant: ["sell"] },
  { en: "sell",      pos: "v.",   zh: "賣",         py: "mài", ant: ["buy"] },
  { en: "give",      pos: "v.",   zh: "給",         py: "gěi", ant: ["take","receive"] },
  { en: "take",      pos: "v.",   zh: "拿;取",      py: "ná" },
  { en: "make",      pos: "v.",   zh: "做;製造",    py: "zuò", syn: ["create","build"] },
  { en: "do",        pos: "v.",   zh: "做",         py: "zuò" },
  { en: "have",      pos: "v.",   zh: "有",         py: "yǒu" },
  { en: "be",        pos: "v.",   zh: "是;在",      py: "shì" },
  { en: "love",      pos: "v./n.",zh: "愛",         py: "ài", ant: ["hate"] },
  { en: "like",      pos: "v.",   zh: "喜歡",       py: "xǐ huān", ant: ["dislike"] },
  { en: "hate",      pos: "v.",   zh: "討厭;恨",    py: "hèn", ant: ["love"] },
  { en: "want",      pos: "v.",   zh: "想要",       py: "xiǎng yào" },
  { en: "need",      pos: "v./n.",zh: "需要",       py: "xū yào" },
  { en: "know",      pos: "v.",   zh: "知道;認識",  py: "zhī dào" },
  { en: "think",     pos: "v.",   zh: "想;認為",    py: "xiǎng" },
  { en: "learn",     pos: "v.",   zh: "學習",       py: "xué xí", deriv: ["learner","learning"] },
  { en: "teach",     pos: "v.",   zh: "教",         py: "jiāo", ant: ["learn"] },
  { en: "help",      pos: "v./n.",zh: "幫助",       py: "bāng zhù", syn: ["assist","aid"] },
  { en: "work",      pos: "v./n.",zh: "工作",       py: "gōng zuò" },
  { en: "rest",      pos: "v./n.",zh: "休息",       py: "xiū xi" },
  { en: "open",      pos: "v.",   zh: "打開",       py: "dǎ kāi", ant: ["close","shut"] },
  { en: "close",     pos: "v.",   zh: "關;近",      py: "guān", ant: ["open"] },
  { en: "start",     pos: "v.",   zh: "開始",       py: "kāi shǐ", syn: ["begin"], ant: ["stop","end"] },
  { en: "stop",      pos: "v.",   zh: "停止",       py: "tíng", ant: ["start","go"] },

  { en: "one",       pos: "num.", zh: "一",         py: "yī" },
  { en: "two",       pos: "num.", zh: "二;兩",      py: "èr" },
  { en: "three",     pos: "num.", zh: "三",         py: "sān" },
  { en: "four",      pos: "num.", zh: "四",         py: "sì" },
  { en: "five",      pos: "num.", zh: "五",         py: "wǔ" },
  { en: "six",       pos: "num.", zh: "六",         py: "liù" },
  { en: "seven",     pos: "num.", zh: "七",         py: "qī" },
  { en: "eight",     pos: "num.", zh: "八",         py: "bā" },
  { en: "nine",      pos: "num.", zh: "九",         py: "jiǔ" },
  { en: "ten",       pos: "num.", zh: "十",         py: "shí" },
  { en: "hundred",   pos: "num.", zh: "百",         py: "bǎi" },
  { en: "thousand",  pos: "num.", zh: "千",         py: "qiān" },

  { en: "Monday",    pos: "n.",   zh: "星期一",     py: "xīng qī yī" },
  { en: "Tuesday",   pos: "n.",   zh: "星期二",     py: "xīng qī èr" },
  { en: "Wednesday", pos: "n.",   zh: "星期三",     py: "xīng qī sān" },
  { en: "Thursday",  pos: "n.",   zh: "星期四",     py: "xīng qī sì" },
  { en: "Friday",    pos: "n.",   zh: "星期五",     py: "xīng qī wǔ" },
  { en: "Saturday",  pos: "n.",   zh: "星期六",     py: "xīng qī liù" },
  { en: "Sunday",    pos: "n.",   zh: "星期日",     py: "xīng qī rì" },
  { en: "today",     pos: "n.",   zh: "今天",       py: "jīn tiān" },
  { en: "tomorrow",  pos: "n.",   zh: "明天",       py: "míng tiān" },
  { en: "yesterday", pos: "n.",   zh: "昨天",       py: "zuó tiān" },
  { en: "morning",   pos: "n.",   zh: "早上",       py: "zǎo shang" },
  { en: "afternoon", pos: "n.",   zh: "下午",       py: "xià wǔ" },
  { en: "evening",   pos: "n.",   zh: "晚上;傍晚",  py: "wǎn shang" },
  { en: "night",     pos: "n.",   zh: "夜晚",       py: "yè wǎn" },

  { en: "red",       pos: "adj./n.",zh: "紅色",     py: "hóng" },
  { en: "blue",      pos: "adj./n.",zh: "藍色",     py: "lán" },
  { en: "green",     pos: "adj./n.",zh: "綠色",     py: "lǜ" },
  { en: "yellow",    pos: "adj./n.",zh: "黃色",     py: "huáng" },
  { en: "black",     pos: "adj./n.",zh: "黑色",     py: "hēi" },
  { en: "white",     pos: "adj./n.",zh: "白色",     py: "bái" },
  { en: "gold",      pos: "n.",     zh: "金;金色",  py: "jīn" },
  { en: "silver",    pos: "n.",     zh: "銀;銀色",  py: "yín" },

  { en: "money",     pos: "n.",   zh: "錢",         py: "qián" },
  { en: "time",      pos: "n.",   zh: "時間",       py: "shí jiān" },
  { en: "year",      pos: "n.",   zh: "年",         py: "nián" },
  { en: "month",     pos: "n.",   zh: "月",         py: "yuè" },
  { en: "week",      pos: "n.",   zh: "星期;週",    py: "xīng qī" },
  { en: "day",       pos: "n.",   zh: "天;日",      py: "tiān", ant: ["night"] },
  { en: "hour",      pos: "n.",   zh: "小時",       py: "xiǎo shí" },
  { en: "minute",    pos: "n.",   zh: "分鐘",       py: "fēn zhōng" },
  { en: "second",    pos: "n.",   zh: "秒;第二",    py: "miǎo" },

  { en: "music",     pos: "n.",   zh: "音樂",       py: "yīn yuè" },
  { en: "song",      pos: "n.",   zh: "歌曲",       py: "gē qǔ" },
  { en: "movie",     pos: "n.",   zh: "電影",       py: "diàn yǐng", syn: ["film"] },
  { en: "game",      pos: "n.",   zh: "遊戲;比賽",  py: "yóu xì" },
  { en: "story",     pos: "n.",   zh: "故事",       py: "gù shì" },

  { en: "peace",     pos: "n.",   zh: "和平",       py: "hé píng", ant: ["war"] },
  { en: "war",       pos: "n.",   zh: "戰爭",       py: "zhàn zhēng", ant: ["peace"] },
  { en: "life",      pos: "n.",   zh: "生命;生活",  py: "shēng huó" },
  { en: "death",     pos: "n.",   zh: "死亡",       py: "sǐ wáng", ant: ["life","birth"] },
  { en: "world",     pos: "n.",   zh: "世界",       py: "shì jiè" },

  { en: "hello",     pos: "interj.", zh: "你好",    py: "nǐ hǎo",
    example: { en: "Hello! How are you?", zh: "你好！你好嗎？" } },
  { en: "goodbye",   pos: "interj.", zh: "再見",    py: "zài jiàn", syn: ["bye"] },
  { en: "yes",       pos: "interj.", zh: "是;對",   py: "shì", ant: ["no"] },
  { en: "no",        pos: "interj.", zh: "不;不是", py: "bù", ant: ["yes"] },
  { en: "please",    pos: "adv.", zh: "請",         py: "qǐng" },
  { en: "thanks",    pos: "n./interj.", zh: "謝謝", py: "xiè xiè", syn: ["thank you"] },
  { en: "sorry",     pos: "adj./interj.", zh: "對不起", py: "duì bù qǐ" },
  { en: "welcome",   pos: "interj./v.",   zh: "歡迎",     py: "huān yíng" },
  { en: "congratulations", pos: "n.",     zh: "恭喜;祝賀", py: "gōng xǐ" },
  { en: "excuse",    pos: "v.",   zh: "原諒;藉口", py: "yuán liàng" },

  // ----- More verbs -----
  { en: "arrive",    pos: "v.",   zh: "到達",       py: "dào dá", ant: ["leave","depart"] },
  { en: "leave",     pos: "v.",   zh: "離開",       py: "lí kāi", ant: ["arrive"] },
  { en: "return",    pos: "v.",   zh: "返回;歸還",  py: "fǎn huí" },
  { en: "send",      pos: "v.",   zh: "寄;發送",    py: "sòng" },
  { en: "bring",     pos: "v.",   zh: "帶來",       py: "dài lái" },
  { en: "carry",     pos: "v.",   zh: "攜帶",       py: "xié dài" },
  { en: "push",      pos: "v.",   zh: "推",         py: "tuī", ant: ["pull"] },
  { en: "pull",      pos: "v.",   zh: "拉",         py: "lā", ant: ["push"] },
  { en: "throw",     pos: "v.",   zh: "扔;投擲",    py: "rēng" },
  { en: "catch",     pos: "v.",   zh: "抓住;接",    py: "zhuō" },
  { en: "find",      pos: "v.",   zh: "找到",       py: "zhǎo", ant: ["lose"] },
  { en: "lose",      pos: "v.",   zh: "失去;輸",    py: "shī", ant: ["find","win"] },
  { en: "win",       pos: "v.",   zh: "贏;獲勝",    py: "yíng", ant: ["lose"] },
  { en: "try",       pos: "v.",   zh: "嘗試",       py: "shì" },
  { en: "change",    pos: "v./n.",zh: "改變;零錢",  py: "gǎi biàn" },
  { en: "finish",    pos: "v.",   zh: "完成",       py: "wán chéng", syn: ["complete"] },
  { en: "prepare",   pos: "v.",   zh: "準備",       py: "zhǔn bèi" },
  { en: "fix",       pos: "v.",   zh: "修理;固定",  py: "xiū lǐ", syn: ["repair"] },
  { en: "break",     pos: "v.",   zh: "打破;弄壞",  py: "pò" },
  { en: "build",     pos: "v.",   zh: "建造",       py: "jiàn", syn: ["construct"] },
  { en: "hold",      pos: "v.",   zh: "拿;握住",    py: "ná" },
  { en: "fall",      pos: "v.",   zh: "跌落;下降",  py: "diē", ant: ["rise"] },
  { en: "rise",      pos: "v.",   zh: "升起;上升",  py: "shēng", ant: ["fall"] },
  { en: "climb",     pos: "v.",   zh: "攀登;爬",    py: "pá" },
  { en: "smile",     pos: "v./n.",zh: "微笑",       py: "wēi xiào" },
  { en: "laugh",     pos: "v.",   zh: "笑",         py: "xiào", ant: ["cry"] },
  { en: "cry",       pos: "v.",   zh: "哭;喊",      py: "kū", ant: ["laugh"] },
  { en: "agree",     pos: "v.",   zh: "同意",       py: "tóng yì", ant: ["disagree"] },
  { en: "believe",   pos: "v.",   zh: "相信",       py: "xiāng xìn" },
  { en: "hope",      pos: "v./n.",zh: "希望",       py: "xī wàng" },
  { en: "dream",     pos: "v./n.",zh: "夢;夢想",    py: "mèng" },
  { en: "remember",  pos: "v.",   zh: "記得",       py: "jì dé", ant: ["forget"] },
  { en: "forget",    pos: "v.",   zh: "忘記",       py: "wàng jì", ant: ["remember"] },
  { en: "understand",pos: "v.",   zh: "明白;理解",  py: "míng bái" },
  { en: "ask",       pos: "v.",   zh: "問;要求",    py: "wèn", ant: ["answer"] },
  { en: "answer",    pos: "v./n.",zh: "回答;答案",  py: "huí dá", ant: ["ask"] },
  { en: "study",     pos: "v.",   zh: "學習;研究",  py: "xué xí" },
  { en: "swim",      pos: "v.",   zh: "游泳",       py: "yóu yǒng" },
  { en: "cook",      pos: "v./n.",zh: "煮;烹飪",    py: "zhǔ" },
  { en: "taste",     pos: "v./n.",zh: "嘗;味道",    py: "cháng" },
  { en: "smell",     pos: "v./n.",zh: "聞;氣味",    py: "wén" },
  { en: "feel",      pos: "v.",   zh: "感覺",       py: "gǎn jué" },
  { en: "hurt",      pos: "v.",   zh: "傷害;痛",    py: "shāng" },
  { en: "save",      pos: "v.",   zh: "拯救;節省",  py: "jiù" },
  { en: "spend",     pos: "v.",   zh: "花費",       py: "huā" },
  { en: "pay",       pos: "v.",   zh: "付款",       py: "fù" },
  { en: "share",     pos: "v.",   zh: "分享",       py: "fēn xiǎng" },
  { en: "count",     pos: "v.",   zh: "數;計算",    py: "shǔ" },
  { en: "wait",      pos: "v.",   zh: "等待",       py: "děng" },
  { en: "stay",      pos: "v.",   zh: "停留",       py: "liú" },
  { en: "live",      pos: "v.",   zh: "居住;活著",  py: "zhù", ant: ["die"] },
  { en: "die",       pos: "v.",   zh: "死",         py: "sǐ", ant: ["live"] },
  { en: "drive",     pos: "v.",   zh: "駕駛",       py: "kāi" },
  { en: "ride",      pos: "v.",   zh: "騎;乘",      py: "qí" },
  { en: "fly",       pos: "v.",   zh: "飛",         py: "fēi" },
  { en: "kill",      pos: "v.",   zh: "殺",         py: "shā" },

  // ----- More adjectives -----
  { en: "heavy",     pos: "adj.", zh: "重",         py: "zhòng", ant: ["light"] },
  { en: "light",     pos: "adj./n.", zh: "輕;光",   py: "qīng", ant: ["heavy","dark"] },
  { en: "thick",     pos: "adj.", zh: "厚;粗",      py: "hòu", ant: ["thin"] },
  { en: "thin",      pos: "adj.", zh: "薄;瘦",      py: "báo", ant: ["thick","fat"] },
  { en: "wide",      pos: "adj.", zh: "寬",         py: "kuān", ant: ["narrow"] },
  { en: "narrow",    pos: "adj.", zh: "窄",         py: "zhǎi", ant: ["wide"] },
  { en: "soft",      pos: "adj.", zh: "軟;柔軟",    py: "ruǎn", ant: ["hard"] },
  { en: "sharp",     pos: "adj.", zh: "鋒利;尖",    py: "lì" },
  { en: "bright",    pos: "adj.", zh: "明亮;聰明",  py: "liàng", ant: ["dark"] },
  { en: "dark",      pos: "adj.", zh: "黑暗;深色",  py: "àn", ant: ["bright","light"] },
  { en: "loud",      pos: "adj.", zh: "大聲",       py: "xiǎng", ant: ["quiet"] },
  { en: "quiet",     pos: "adj.", zh: "安靜",       py: "jìng", ant: ["loud","noisy"] },
  { en: "simple",    pos: "adj.", zh: "簡單",       py: "jiǎn dān", syn: ["easy"], ant: ["complex"] },
  { en: "full",      pos: "adj.", zh: "滿",         py: "mǎn", ant: ["empty"] },
  { en: "empty",     pos: "adj.", zh: "空",         py: "kōng", ant: ["full"] },
  { en: "sweet",     pos: "adj.", zh: "甜",         py: "tián", ant: ["bitter","sour"] },
  { en: "sour",      pos: "adj.", zh: "酸",         py: "suān" },
  { en: "bitter",    pos: "adj.", zh: "苦",         py: "kǔ", ant: ["sweet"] },
  { en: "salty",     pos: "adj.", zh: "鹹",         py: "xián" },
  { en: "spicy",     pos: "adj.", zh: "辣",         py: "là" },
  { en: "fresh",     pos: "adj.", zh: "新鮮",       py: "xīn xiān" },
  { en: "alive",     pos: "adj.", zh: "活的",       py: "huó", ant: ["dead"] },
  { en: "dead",      pos: "adj.", zh: "死的",       py: "sǐ", ant: ["alive"] },
  { en: "healthy",   pos: "adj.", zh: "健康",       py: "jiàn kāng", ant: ["sick"] },
  { en: "sick",      pos: "adj.", zh: "生病",       py: "bìng", ant: ["healthy"] },
  { en: "strong",    pos: "adj.", zh: "強壯",       py: "qiáng", ant: ["weak"] },
  { en: "weak",      pos: "adj.", zh: "弱",         py: "ruò", ant: ["strong"] },
  { en: "brave",     pos: "adj.", zh: "勇敢",       py: "yǒng gǎn" },
  { en: "kind",      pos: "adj./n.", zh: "善良;種類", py: "shàn" },
  { en: "polite",    pos: "adj.", zh: "有禮貌",     py: "lǐ mào" },
  { en: "honest",    pos: "adj.", zh: "誠實",       py: "chéng shí" },
  { en: "lazy",      pos: "adj.", zh: "懶",         py: "lǎn" },
  { en: "smart",     pos: "adj.", zh: "聰明",       py: "cōng míng", syn: ["clever"], ant: ["stupid"] },
  { en: "funny",     pos: "adj.", zh: "有趣;好笑",  py: "yǒu qù" },
  { en: "calm",      pos: "adj.", zh: "平靜;鎮定",  py: "píng jìng" },
  { en: "lonely",    pos: "adj.", zh: "孤單;寂寞",  py: "gū dān" },
  { en: "friendly",  pos: "adj.", zh: "友善",       py: "yǒu shàn" },
  { en: "famous",    pos: "adj.", zh: "著名",       py: "zhù míng" },
  { en: "important", pos: "adj.", zh: "重要",       py: "zhòng yào" },
  { en: "useful",    pos: "adj.", zh: "有用",       py: "yǒu yòng", ant: ["useless"] },
  { en: "real",      pos: "adj.", zh: "真實的",     py: "zhēn", ant: ["fake"] },
  { en: "normal",    pos: "adj.", zh: "正常",       py: "zhèng cháng" },
  { en: "strange",   pos: "adj.", zh: "奇怪",       py: "qí guài" },
  { en: "modern",    pos: "adj.", zh: "現代",       py: "xiàn dài", ant: ["ancient"] },
  { en: "ancient",   pos: "adj.", zh: "古代",       py: "gǔ dài", ant: ["modern"] },

  // ----- More food / drink -----
  { en: "cake",      pos: "n.",   zh: "蛋糕",       py: "dàn gāo" },
  { en: "cookie",    pos: "n.",   zh: "餅乾",       py: "bǐng gān" },
  { en: "pizza",     pos: "n.",   zh: "披薩",       py: "pī sà" },
  { en: "sandwich",  pos: "n.",   zh: "三明治",     py: "sān míng zhì" },
  { en: "hamburger", pos: "n.",   zh: "漢堡",       py: "hàn bǎo" },
  { en: "candy",     pos: "n.",   zh: "糖果",       py: "táng guǒ" },
  { en: "chocolate", pos: "n.",   zh: "朱古力",     py: "qiǎo kè lì" },
  { en: "butter",    pos: "n.",   zh: "牛油",       py: "niú yóu" },
  { en: "cheese",    pos: "n.",   zh: "芝士;乳酪",  py: "rǔ lào" },
  { en: "juice",     pos: "n.",   zh: "果汁",       py: "guǒ zhī" },
  { en: "beer",      pos: "n.",   zh: "啤酒",       py: "pí jiǔ" },
  { en: "wine",      pos: "n.",   zh: "葡萄酒",     py: "pú táo jiǔ" },
  { en: "salad",     pos: "n.",   zh: "沙律;沙拉",  py: "shā lā" },
  { en: "breakfast", pos: "n.",   zh: "早餐",       py: "zǎo cān" },
  { en: "lunch",     pos: "n.",   zh: "午餐",       py: "wǔ cān" },
  { en: "dinner",    pos: "n.",   zh: "晚餐",       py: "wǎn cān" },
  { en: "dessert",   pos: "n.",   zh: "甜品",       py: "tián pǐn" },

  // ----- More animals -----
  { en: "bear",      pos: "n.",   zh: "熊",         py: "xióng" },
  { en: "fox",       pos: "n.",   zh: "狐狸",       py: "hú lí" },
  { en: "deer",      pos: "n.",   zh: "鹿",         py: "lù" },
  { en: "frog",      pos: "n.",   zh: "青蛙",       py: "qīng wā" },
  { en: "dolphin",   pos: "n.",   zh: "海豚",       py: "hǎi tún" },
  { en: "whale",     pos: "n.",   zh: "鯨魚",       py: "jīng yú" },
  { en: "owl",       pos: "n.",   zh: "貓頭鷹",     py: "māo tóu yīng" },
  { en: "duck",      pos: "n.",   zh: "鴨",         py: "yā" },
  { en: "goose",     pos: "n.",   zh: "鵝",         py: "é" },
  { en: "bee",       pos: "n.",   zh: "蜜蜂",       py: "mì fēng" },
  { en: "butterfly", pos: "n.",   zh: "蝴蝶",       py: "hú dié" },
  { en: "ant",       pos: "n.",   zh: "螞蟻",       py: "mǎ yǐ" },
  { en: "spider",    pos: "n.",   zh: "蜘蛛",       py: "zhī zhū" },

  // ----- More body -----
  { en: "neck",      pos: "n.",   zh: "頸;脖子",    py: "jǐng" },
  { en: "shoulder",  pos: "n.",   zh: "肩膀",       py: "jiān bǎng" },
  { en: "back",      pos: "n.",   zh: "背",         py: "bèi" },
  { en: "stomach",   pos: "n.",   zh: "胃;肚子",    py: "wèi" },
  { en: "knee",      pos: "n.",   zh: "膝蓋",       py: "xī gài" },
  { en: "finger",    pos: "n.",   zh: "手指",       py: "shǒu zhǐ" },
  { en: "skin",      pos: "n.",   zh: "皮膚",       py: "pí fū" },
  { en: "blood",     pos: "n.",   zh: "血",         py: "xuè" },
  { en: "brain",     pos: "n.",   zh: "腦",         py: "nǎo" },
  { en: "bone",      pos: "n.",   zh: "骨頭",       py: "gǔ tóu" },

  // ----- Clothing / furniture / home -----
  { en: "shirt",     pos: "n.",   zh: "襯衫",       py: "chèn shān" },
  { en: "pants",     pos: "n.",   zh: "褲子",       py: "kù zi" },
  { en: "shoes",     pos: "n.",   zh: "鞋",         py: "xié" },
  { en: "hat",       pos: "n.",   zh: "帽子",       py: "mào zi" },
  { en: "coat",      pos: "n.",   zh: "外套",       py: "wài tào" },
  { en: "table",     pos: "n.",   zh: "桌子",       py: "zhuō zi" },
  { en: "chair",     pos: "n.",   zh: "椅子",       py: "yǐ zi" },
  { en: "bed",       pos: "n.",   zh: "床",         py: "chuáng" },
  { en: "sofa",      pos: "n.",   zh: "沙發",       py: "shā fā" },
  { en: "lamp",      pos: "n.",   zh: "燈",         py: "dēng" },
  { en: "mirror",    pos: "n.",   zh: "鏡子",       py: "jìng zi" },
  { en: "clock",     pos: "n.",   zh: "鐘",         py: "zhōng" },
  { en: "door",      pos: "n.",   zh: "門",         py: "mén" },
  { en: "window",    pos: "n.",   zh: "窗戶",       py: "chuāng hù" },
  { en: "kitchen",   pos: "n.",   zh: "廚房",       py: "chú fáng" },
  { en: "bedroom",   pos: "n.",   zh: "睡房;臥室",  py: "wò shì" },
  { en: "bathroom",  pos: "n.",   zh: "浴室;洗手間",py: "yù shì" },

  // ----- Tech / business -----
  { en: "software",  pos: "n.",   zh: "軟件",       py: "ruǎn jiàn" },
  { en: "app",       pos: "n.",   zh: "應用程式",   py: "yìng yòng" },
  { en: "website",   pos: "n.",   zh: "網站",       py: "wǎng zhàn" },
  { en: "password",  pos: "n.",   zh: "密碼",       py: "mì mǎ" },
  { en: "file",      pos: "n.",   zh: "檔案;文件",  py: "dàng àn" },
  { en: "video",     pos: "n.",   zh: "影片",       py: "yǐng piàn" },
  { en: "photo",     pos: "n.",   zh: "照片",       py: "zhào piàn" },
  { en: "wifi",      pos: "n.",   zh: "無線網絡",   py: "wú xiàn" },

  // ----- Months / seasons / directions -----
  { en: "January",   pos: "n.",   zh: "一月",       py: "yī yuè" },
  { en: "February",  pos: "n.",   zh: "二月",       py: "èr yuè" },
  { en: "March",     pos: "n.",   zh: "三月",       py: "sān yuè" },
  { en: "April",     pos: "n.",   zh: "四月",       py: "sì yuè" },
  { en: "May",       pos: "n.",   zh: "五月",       py: "wǔ yuè" },
  { en: "June",      pos: "n.",   zh: "六月",       py: "liù yuè" },
  { en: "July",      pos: "n.",   zh: "七月",       py: "qī yuè" },
  { en: "August",    pos: "n.",   zh: "八月",       py: "bā yuè" },
  { en: "September", pos: "n.",   zh: "九月",       py: "jiǔ yuè" },
  { en: "October",   pos: "n.",   zh: "十月",       py: "shí yuè" },
  { en: "November",  pos: "n.",   zh: "十一月",     py: "shí yī yuè" },
  { en: "December",  pos: "n.",   zh: "十二月",     py: "shí èr yuè" },
  { en: "spring",    pos: "n.",   zh: "春天",       py: "chūn tiān" },
  { en: "summer",    pos: "n.",   zh: "夏天",       py: "xià tiān" },
  { en: "autumn",    pos: "n.",   zh: "秋天",       py: "qiū tiān", syn: ["fall"] },
  { en: "winter",    pos: "n.",   zh: "冬天",       py: "dōng tiān" },
  { en: "north",     pos: "n.",   zh: "北",         py: "běi", ant: ["south"] },
  { en: "south",     pos: "n.",   zh: "南",         py: "nán", ant: ["north"] },
  { en: "east",      pos: "n.",   zh: "東",         py: "dōng", ant: ["west"] },
  { en: "west",      pos: "n.",   zh: "西",         py: "xī", ant: ["east"] },
  { en: "up",        pos: "adv.", zh: "上",         py: "shàng", ant: ["down"] },
  { en: "down",      pos: "adv.", zh: "下",         py: "xià", ant: ["up"] },

  // ----- Abstract / feelings / travel -----
  { en: "idea",      pos: "n.",   zh: "想法;主意",  py: "xiǎng fǎ" },
  { en: "plan",      pos: "n./v.",zh: "計劃",       py: "jì huà" },
  { en: "problem",   pos: "n.",   zh: "問題",       py: "wèn tí" },
  { en: "solution",  pos: "n.",   zh: "解決方法",   py: "jiě jué" },
  { en: "success",   pos: "n.",   zh: "成功",       py: "chéng gōng", ant: ["failure"] },
  { en: "failure",   pos: "n.",   zh: "失敗",       py: "shī bài", ant: ["success"] },
  { en: "luck",      pos: "n.",   zh: "運氣",       py: "yùn qì" },
  { en: "danger",    pos: "n.",   zh: "危險",       py: "wēi xiǎn", ant: ["safety"] },
  { en: "safety",    pos: "n.",   zh: "安全",       py: "ān quán", ant: ["danger"] },
  { en: "freedom",   pos: "n.",   zh: "自由",       py: "zì yóu" },
  { en: "truth",     pos: "n.",   zh: "真相;事實",  py: "zhēn xiàng" },
  { en: "secret",    pos: "n.",   zh: "秘密",       py: "mì mì" },
  { en: "joy",       pos: "n.",   zh: "喜悅",       py: "xǐ yuè" },
  { en: "fear",      pos: "n.",   zh: "恐懼",       py: "kǒng jù" },
  { en: "pride",     pos: "n.",   zh: "驕傲",       py: "jiāo ào" },
  { en: "ticket",    pos: "n.",   zh: "票",         py: "piào" },
  { en: "passport",  pos: "n.",   zh: "護照",       py: "hù zhào" },
  { en: "hotel",     pos: "n.",   zh: "酒店;旅館",  py: "lǚ guǎn" },
  { en: "restaurant",pos: "n.",   zh: "餐廳",       py: "cān tīng" },
  { en: "beach",     pos: "n.",   zh: "海灘",       py: "hǎi tān" },
  { en: "museum",    pos: "n.",   zh: "博物館",     py: "bó wù guǎn" },
  { en: "map",       pos: "n.",   zh: "地圖",       py: "dì tú" },
  { en: "vacation",  pos: "n.",   zh: "假期",       py: "jià qī", syn: ["holiday"] },
  { en: "suitcase",  pos: "n.",   zh: "行李箱",     py: "xíng lǐ xiāng" },

  // ----- Misc -----
  { en: "size",      pos: "n.",   zh: "尺寸;大小",  py: "chǐ cùn" },
  { en: "weight",    pos: "n.",   zh: "重量",       py: "zhòng liàng" },
  { en: "length",    pos: "n.",   zh: "長度",       py: "cháng dù" },
  { en: "shape",     pos: "n.",   zh: "形狀",       py: "xíng zhuàng" },
  { en: "circle",    pos: "n.",   zh: "圓",         py: "yuán" },
  { en: "square",    pos: "n.",   zh: "方;廣場",    py: "fāng" },
  { en: "triangle",  pos: "n.",   zh: "三角形",     py: "sān jiǎo" }
];

/* ============================================================
 * Chinese-Chinese mini-dictionary (中辭) — for the 中辭 mode.
 * { word, py, pos, def }
 * ============================================================ */
window.CNDICT = [
  { word: "蘋果", py: "píng guǒ", pos: "名", def: "一種水果，多為紅色或青綠色，圓形，味甜可口。" },
  { word: "香蕉", py: "xiāng jiāo", pos: "名", def: "熱帶水果，黃色長條形，味甜，富含營養。" },
  { word: "老師", py: "lǎo shī", pos: "名", def: "在學校或機構中傳授知識的人。" },
  { word: "學生", py: "xué shēng", pos: "名", def: "在學校學習的人。" },
  { word: "朋友", py: "péng yǒu", pos: "名", def: "彼此有交情、相互信任的人。" },
  { word: "家庭", py: "jiā tíng", pos: "名", def: "由婚姻、血緣或收養關係組成的社會單位。" },
  { word: "國家", py: "guó jiā", pos: "名", def: "由領土、人民和政府組成的政治實體。" },
  { word: "歷史", py: "lì shǐ", pos: "名", def: "過去發生的事件及其紀錄。" },
  { word: "文化", py: "wén huà", pos: "名", def: "人類在歷史中創造的物質和精神財富的總稱。" },
  { word: "科學", py: "kē xué", pos: "名", def: "通過觀察、實驗來認識自然規律的知識體系。" },
  { word: "電腦", py: "diàn nǎo", pos: "名", def: "電子計算機；用於處理資料的電子設備。" },
  { word: "電話", py: "diàn huà", pos: "名", def: "利用電訊技術進行遠距離通話的裝置。" },
  { word: "字典", py: "zì diǎn", pos: "名", def: "彙集字詞並加以解釋的工具書。" },
  { word: "智慧", py: "zhì huì", pos: "名", def: "辨析判斷、發明創造的能力。" },
  { word: "勇敢", py: "yǒng gǎn", pos: "形", def: "有膽量，不怕困難或危險。" },
  { word: "誠實", py: "chéng shí", pos: "形", def: "真誠老實，不說謊話。" },
  { word: "美麗", py: "měi lì", pos: "形", def: "好看、漂亮，使人感到愉悅。" },
  { word: "快樂", py: "kuài lè", pos: "形", def: "感到滿足與愉悅；幸福。" },
  { word: "幸福", py: "xìng fú", pos: "形/名", def: "稱心如意，生活美滿；快樂的境況。" },
  { word: "希望", py: "xī wàng", pos: "動/名", def: "心中盼望某事實現；對未來的期待。" },
  { word: "夢想", py: "mèng xiǎng", pos: "名", def: "心中所追求的理想或願望。" },
  { word: "自由", py: "zì yóu", pos: "形/名", def: "不受限制，能依自己意志行事的狀態。" },
  { word: "和平", py: "hé píng", pos: "名", def: "沒有戰爭與紛爭的安寧狀態。" },
  { word: "音樂", py: "yīn yuè", pos: "名", def: "用聲音的高低、長短、強弱組成的藝術。" },
  { word: "藝術", py: "yì shù", pos: "名", def: "以形象表現美感的人類創作活動。" },
  { word: "宇宙", py: "yǔ zhòu", pos: "名", def: "包含一切時空、物質與能量的整體。" },
  { word: "山水", py: "shān shuǐ", pos: "名", def: "山與水；自然風景。" },
  { word: "明月", py: "míng yuè", pos: "名", def: "明亮的月亮；常用於詩詞中寄託情思。" },
  { word: "故鄉", py: "gù xiāng", pos: "名", def: "出生或長期居住的地方；家鄉。" },
  { word: "青春", py: "qīng chūn", pos: "名", def: "年輕的時光；十多至二十多歲的階段。" }
];

/* ============================================================
 * 唐詩三百首 — selected works
 * ============================================================ */
window.POEMS = [
  { title: "靜夜思", author: "李白", dyn: "唐",
    lines: ["床前明月光", "疑是地上霜", "舉頭望明月", "低頭思故鄉"] },
  { title: "春曉", author: "孟浩然", dyn: "唐",
    lines: ["春眠不覺曉", "處處聞啼鳥", "夜來風雨聲", "花落知多少"] },
  { title: "登鸛雀樓", author: "王之渙", dyn: "唐",
    lines: ["白日依山盡", "黃河入海流", "欲窮千里目", "更上一層樓"] },
  { title: "憫農", author: "李紳", dyn: "唐",
    lines: ["鋤禾日當午", "汗滴禾下土", "誰知盤中飧", "粒粒皆辛苦"] },
  { title: "望廬山瀑布", author: "李白", dyn: "唐",
    lines: ["日照香爐生紫煙", "遙看瀑布掛前川", "飛流直下三千尺", "疑是銀河落九天"] },
  { title: "早發白帝城", author: "李白", dyn: "唐",
    lines: ["朝辭白帝彩雲間", "千里江陵一日還", "兩岸猿聲啼不住", "輕舟已過萬重山"] },
  { title: "楓橋夜泊", author: "張繼", dyn: "唐",
    lines: ["月落烏啼霜滿天", "江楓漁火對愁眠", "姑蘇城外寒山寺", "夜半鐘聲到客船"] },
  { title: "江雪", author: "柳宗元", dyn: "唐",
    lines: ["千山鳥飛絕", "萬徑人蹤滅", "孤舟蓑笠翁", "獨釣寒江雪"] },
  { title: "黃鶴樓", author: "崔顥", dyn: "唐",
    lines: ["昔人已乘黃鶴去", "此地空餘黃鶴樓", "黃鶴一去不復返", "白雲千載空悠悠",
            "晴川歷歷漢陽樹", "芳草萋萋鸚鵡洲", "日暮鄉關何處是", "煙波江上使人愁"] },
  { title: "相思", author: "王維", dyn: "唐",
    lines: ["紅豆生南國", "春來發幾枝", "願君多采擷", "此物最相思"] },
  { title: "送別", author: "王維", dyn: "唐",
    lines: ["山中相送罷", "日暮掩柴扉", "春草明年綠", "王孫歸不歸"] },
  { title: "九月九日憶山東兄弟", author: "王維", dyn: "唐",
    lines: ["獨在異鄉為異客", "每逢佳節倍思親", "遙知兄弟登高處", "遍插茱萸少一人"] },
  { title: "登高", author: "杜甫", dyn: "唐",
    lines: ["風急天高猿嘯哀", "渚清沙白鳥飛回", "無邊落木蕭蕭下", "不盡長江滾滾來",
            "萬里悲秋常作客", "百年多病獨登臺", "艱難苦恨繁霜鬢", "潦倒新停濁酒杯"] },
  { title: "春望", author: "杜甫", dyn: "唐",
    lines: ["國破山河在", "城春草木深", "感時花濺淚", "恨別鳥驚心",
            "烽火連三月", "家書抵萬金", "白頭搔更短", "渾欲不勝簪"] },
  { title: "回鄉偶書", author: "賀知章", dyn: "唐",
    lines: ["少小離家老大回", "鄉音無改鬢毛衰", "兒童相見不相識", "笑問客從何處來"] },
  { title: "涼州詞", author: "王翰", dyn: "唐",
    lines: ["葡萄美酒夜光杯", "欲飲琵琶馬上催", "醉臥沙場君莫笑", "古來征戰幾人回"] },
  { title: "出塞", author: "王昌齡", dyn: "唐",
    lines: ["秦時明月漢時關", "萬里長征人未還", "但使龍城飛將在", "不教胡馬度陰山"] },
  { title: "黃河遠上", author: "王之渙", dyn: "唐",
    lines: ["黃河遠上白雲間", "一片孤城萬仞山", "羌笛何須怨楊柳", "春風不度玉門關"] }
];

